services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-cartesian-explosion
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cartesian_explosion
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cartesian_explosion"]
      interval: 5s
      timeout: 5s
      retries: 10
