services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-bulk-insert
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bulk_insert_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_bulk_insert_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bulk_insert_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_bulk_insert_data:
